language: python
cache: pip
install:
  - pip install tox

jobs:
  include:
    - stage: syntax
      script: tox
      python: 3.6
      env: TOXENV=syntax
    - stage: test
      script: tox
      python: 3.7
      env: TOXENV=py37
    - stage: test
      script: tox
      python: 3.8
      env: TOXENV=py38
    - stage: test
      script: tox
      python: 3.9
      env: TOXENV=py39
